import os, os.path, subprocess

def bytes_to_int(bytes):
    result = 0
    for b in bytes:
        result = (result << 8) + int(b)
    return result

def gen_mdt(fn, offset):
	with open(fn, "rb") as f:
		f.read(16)
		width = bytes_to_int(f.read(4)) >> 3
		height = bytes_to_int(f.read(4)) >> 3
	outfn = fn[:-4] + ".mdt"
	with open(outfn, "w") as f:
		f.write("input ../" + fn + "\n")
		f.write("output ../" + fn[:-4] + ".pat" + "\n")
		f.write("output2 ../" + fn[:-4] + ".map" + "\n")
		f.write("offset " + str(offset) + "\n")
		f.write("map 0 0 " + str(width) + " " + str(height) + "\n")

sprTable = [
# Use PAL_Sega
["sega.png"   ,12,4],
["sega2.png"   ,12,4],
["quote.png",2,2],
["air.png",7,1],
["air_ja.png",7,1],
["hud2.png",8,4],
["pointer.png",2,2],
["armsimage.png",2,2],
["armsimage_menu.png",2,2],
["misery.png",2,2],
["telemenu.png",4,2],
["fish.png",2,2],
["critbig.png",3,3],
["jelly.png",2,2],
["kulala.png",6,3],
["missileb1.png",2,2],
["missileb2.png",2,2],
["bladeb1.png",5,2],
["bladeb2.png",3,3],
["bladeb3king.png",3,3],
["bladeb3slash.png" ,2,2],
["quotele.png",2,2],
["bubble.png",3,3],
["mgun.png",6,1],
["mgunb1.png",2,2],
["mgunb2.png",2,2],
["mgunb3.png",2,2],
["headbump.png",1,1],
["redflowers.png" ,6,2],
["basushot.png",2,2],
["ikachan.png",2,2],
["droll2.png",4,5],
["gunfish.png",3,3],
["boost.png",4,1],
["happything.png" ,2,2],
["dragonfly.png",2,2],
["z.png",1,1],
["redflowers3.png" ,6,4],
["mimisleep.png",2,2],
["bubb1.png",1,1],
["bubb2.png",1,1],
["bubb3.png",1,1],
["nemb1h.png",3,2],
["nemb1v.png",2,3],
["nemb2h.png",3,2],
["nemb2v.png",2,3],
["nemb3h.png",3,2],
["nemb3v.png",2,3],
["qmark.png",1,1],
["ballos.png"  ,15 ,15],
["ballosp.png",6,5],
["ballos_eye.png",3,2],
["ballos_plat.png",4,2],
["ballos_ball.png",4,4],
["ballos_smile.png",4,2],
["butered.png",3,2],
["butered2.png",2,2],
["spurb1.png",2,2],
["spurb2.png",2,2],
["spurb3.png",2,2],
["polar.png",6,1],
["polarb1.png",2,2],
["polarb2.png",2,2],
["polarb3.png",2,2],
["fireball.png",6,1],
["fireballb1.png",2,2],
["fireballb2.png",2,2],
["fireballb3.png",2,2],
["missiles.png",6,1],
["supermissl.png",6,1],
["snake.png",6,1],
["bubbler.png",6,1],
["nemesis.png",6,1],
["chest.png",2,2],
["save.png",2,2],
["refill.png",2,2],
["door.png",2,3],
["tele.png",3,4],
["trap.png",4,3],
["lifeup.png",2,2],
["bed.png",4,2],
["fire.png",2,2],
["sign.png",2,2],
["smoke.png",2,2],
["sparkle.png",2,2],
["energysm.png",1,1],
["energylg.png",2,2],
["doore.png",2,3],
["bat.png",2,2],
["spikes.png",2,2],
["behem.png",4,3],
["basil.png",4,2],
["balrog.png",5,3],
["heart.png",2,2],
["forcefield.png",2,2],
["computer.png",4,3],
["blackboard.png",5,4],
["savesign.png",2,2],
["wave.png",2,2],
["platform.png",4,2],
["pignon.png",2,2],
["pignonb.png",3,3],
["chestopen.png",2,1],
["key.png",2,2],
["terminal.png",2,3],
["gkeeper.png",4,3],
["fan.png",2,2],
["malco.png",2,3],
["pot.png",2,2],
["press.png",2,3],
["pressh.png",3,2],
["cage.png",4,3],
["energyshot.png",2,2],
["missilep.png",2,2],
["telelight.png",2,2],
["puppy.png",2,2],
["table.png",3,2],
["manshot.png",2,3],
["skullstep.png",4,3],
["frogshot.png",2,2],
["toroblock.png",2,2],
["bigdoorframe.png" ,4,4],
["bigdoor.png",2,3],
["powerscreen.png" ,2,2],
["hey.png",2,2],
["sprinkler.png",2,2],
["kingsword.png",2,2],
["drop.png",1,1],
["redflowers2.png" ,4,2],
["jumpthing.png" ,2,2],
["surfacerobot.png" ,2,2],
["grate.png",2,2],
["energycapsule.png" ,2,2],
["musldr.png",5,6],
["docboss.png",3,4],
["docbat.png",2,2],
["reddot.png",1,1],
["docshot.png",2,2],
["jailbars.png",2,4],
["dragonshot.png" ,2,3],
["lightning.png"     ,2 ,24],
["heli.png"   ,16,8],
["heliblade.png"     ,14,2],
["heliblade2.png",9,2],
["redcrystal.png" ,1,2],
["levelup.png",7,2],
["levelup_ja.png",7,2],
["leveldown.png",7,2],
["leveldown_ja.png" ,7,2],
["heavypress.png"  ,10 ,5],
["hp_lightning.png"  ,2 ,12],
["hp_charge.png",2,2],
["butearw.png",2,2],
["rolling.png",2,2],
["deleet.png",3,3],
["target.png",3,3],
["ghostdog.png",2,2],
["hp_lit.png",4,4],
["balrog_fly.png",5,3],
["balrog_medic.png",5,3],
["puppy_baby.png",2,1],
["empty.png",5,1],
["empty_ja.png",5,1],
["blood.png"          ,7,4],
["docdie.png"         ,4,6],
["drop2.png"          ,1,1],
["transmg.png"        ,4,6],
["critcave.png",2,2],
["mazeblock.png",4,4],
["critterp.png",2,2],
["gaudi.png",3,3],
["labshot.png",2,2],
["gaudishot.png",2,2],
["gaudiarmor.png",3,3],
["fuzzcore.png",4,4],
["fuzz.png",2,2],
["corething.png",4,4],
["corethingshot.png" ,2,4],
["buggy.png",4,4],
["buggy2.png",8,2],
["gaudimerch.png",4,3],
["buyobase.png",4,4],
["buyo.png",2,2],
["gaudiegg.png",3,3],
["coreshutter.png",2,4],
["corebigshutter.png" ,4,4],
["corelift.png",2,2],
["gratemouth.png" ,2,2],
["core.png"          ,8 ,12],
["coreback.png"     ,10 ,12],
["coremini1.png",4,4],
["coremini2.png",4,4],
["coremini3.png",3,4],
["coremini4.png",4,1],
["coremini5.png",2,1],
["coreshot1.png",2,2],
["coreshot2.png",3,2],
["coreshot3.png",1,2],
["coreshot4.png",4,4],
["ironhblk.png",4,4],
["smstal.png",2,2],
["lgstal.png",2,4],
["nightshade.png" ,6,6],
["nightshot.png",4,2],
["sandcroc2.png",6,4],
["ucore.png"         ,8 ,12],
["ucoreback.png"  ,10 ,12],
["ucoreminif.png",4,4],
["ucoreminib.png",3,4],
["ucoreminit.png",4,1],
["ucoreminie.png",2,1],
["ucoremouth.png",7,4],
["jailbars2.png" ,8,4],
["cage2.png",4,4],
["block.png",4,4],
["blockm.png",2,2],
["rock.png",2,2],
["statue.png",4,5],
["cloud1.png",4,4],
["cloud2.png",4,4],
["cloud3.png",3,3],
["cloud4.png",4,2],
["gaudi_end.png",3,2],
["kazuma.png",2,3],
["cthu.png",2,3],
["crithg.png",2,2],
["basu.png",3,3],
["btlhg.png",2,2],
["btlhb.png",2,2],
["toroko.png",2,2],
["sue.png",2,2],
["king.png",2,2],
["igor.png",5,5],
["robot.png",2,2],
["kazucom.png",2,3],
["kanpachi.png",3,2],
["jack.png",2,2],
["mahin.png",2,2],
["santa.png",2,2],
["mannan.png",3,4],
["curly.png",2,2],
["curlyb.png",4,3],
["sandstone.png",4,4],
["sandcroc.png",6,4],
["polish.png",4,4],
["baby.png",2,2],
["crow.png",4,4],
["armadillo.png",4,2],
["booster.png",2,2],
["doctor.png",3,4],
["torokoboss.png",4,4],
["toroflower.png",2,2],
["frog.png",3,4],
["frogsm.png",2,2],
["cirlymimi.png",2,2],
["suecom.png",2,3],
["drgero.png",2,2],
["nurse.png",2,2],
["omega.png",9,7],
["omegaleg.png",4,4],
["omegashot.png",2,2],
["omgstrut.png",3,2],
["skelfeet.png",3,2],
["skeleton.png",4,4],
["bone.png",2,2],
["ironh.png",8,3],
["blowfish.png",2,2],
["momo.png",2,3],
["itoh.png",2,2],
["droll.png",4,5],
["droll3.png",4,5],
["bigbat.png",4,4],
["blackbat.png",2,2],
["rocket.png",4,2],
["drollshot.png",3,3],
["cat.png",2,2],
["skydragon.png",5,5],
["kanpachi2.png",2,3],
["chie.png",2,2],
["jailmimi.png",2,2],
["shovelmimi.png" ,2,2],
["megane.png",2,2],
["oldmimi.png",2,2],
["bucket.png",2,2],
["chako2.png",2,2],
["ravil.png",3,3],
["littles.png",1,1],
["bute.png",3,2],
["mesa.png",4,4],
["grndevil.png",2,2],
["turning_human.png",2,3],
["ahchoo_en.png",2,2],
["ahchoo_ja.png",2,2],
["balrog_passngr.png",2,2],
["doctorintro.png",2,4],
["crownintro.png",2,2],
["misery_wind.png",2,3],
["gunsmith.png",2,2],
["sanda.png",6,4],
["flower.png",2,2],
["balfrog1.png",9,8],
["balfrog2.png",3,3],
["chaco.png",2,2],
["jenka.png",2,2],
["dark.png",5,3],
["darkbubble.png",2,2],
["darkdie.png"        ,4,3],
["xfishy.png",2,2],
["xtarget.png",2,2],
["xtread.png",8,4],
["xdoor.png",6,6],
["xinternals.png" ,9,5],
["xbody.png",9,4],
["xcat.png",6,9],
["boulder.png",7,5],
["babydragon.png" ,5,4],
["basu2.png",3,3],
["btl2.png",2,2],
["wisp.png",5,5],
["numbubble.png",2,2],
["critaqua.png",2,2],
["sisbody.png",4,5],
["sishead.png",4,4],
["dripred.png",1,2],
["critterred.png" ,2,2],
["batred.png",2,2],
["bubred.png",1,1],
["drollred.png",4,5],
["drollshotred.png" ,3,3],
["mapignon.png",2,2],
["misery2.png" ,2,2],
["sue2.png" ,2,2],
["mizamisery.png" ,4,4],
["mizasue.png",4,4],
["mizabat.png",2,2],
["mizacritter.png" ,2,2],
["mizaring.png",2,2],
["mizashock.png",2,4],
["mizafish.png",2,2],
["mizapellet.png" ,1,1],
["mizarock.png",3,3],
["bubbleintro.png",6,6],
["itemimage.png",3,2],
["itemimage_g.png" ,3,2],
	]

sprTableExtra = [
["itemwindow.png" 		,6,3],
["prompt.png" 			,8,3],
["prompt_ja.png" 		,8,3],
["xxIsland.png" 		,5,3],
]

casts = ["casts.png",3,3]
if __name__ == '__main__':
	folder = "../res/Stage/"
	folders = ['White/', 'Mimi/', 'Maze/', 'Hell/', 'Eggs/']
	wd = os.getcwd()
	os.chdir(folder)
	for fn in os.listdir("."):
		if fn.startswith("Prt") and fn.endswith(".png"):
			subprocess.run(['grit', fn, '-gt', '-gB4', '-ftb', '-m!', '-fh!'])
	for f in folders:
		os.chdir(wd)
		os.chdir(folder + f)
		for fn in os.listdir("."):
			if fn.startswith("Prt") and fn.endswith(".png"):
				subprocess.run(['grit', fn, '-gt', '-gB4', '-ftb', '-m!', '-fh!'])
	os.chdir(wd)
	os.chdir("../res/back/")
	for fn in os.listdir("."):
		if fn.startswith("bk") and (fn.endswith(".png") or fn.endswith(".bmp")):
			subprocess.run(['grit', fn, '-gt', '-gB4', '-ftb', '-m!', '-fh!'])
	os.chdir(wd)
	os.chdir("../res/sprite/")
#	for fn in os.listdir("."):
#		if fn.endswith(".png"):
#			subprocess.run(['grit', fn, '-gt', '-gB4', '-ftb', '-m!', '-fh!', '-Mh2', '-Mw2'])
	for entry in sprTable:
		subprocess.run(['grit', entry[0], '-gt', '-gB4', '-ftb', '-m!', '-fh!', '-Mw' + str(entry[1]), '-Mh' + str(entry[2])])
	os.chdir(wd)
	os.chdir("../res/")
	for entry in sprTableExtra:
		subprocess.run(['grit', entry[0], '-gt', '-gB4', '-ftb', '-m!', '-fh!', '-Mw' + str(entry[1]), '-Mh' + str(entry[2])])
	os.chdir("credits")
	subprocess.run(['grit', casts[0], '-gt', '-gB4', '-ftb', '-m!', '-fh!', '-Mw' + str(casts[1]), '-Mh' + str(casts[2])])
