#include "common.h"
#include "bank_data.h"
#include "tables.h"

#include "soundbank.h"

const song_info_def song_info[SONG_COUNT] = {

};

const song_info_def song_info_xm[SONG_COUNT] = {
	{ 0, 			"Silence" },
	{ MOD_WANPAKU, 	"Mischievous Robot" },
	{ MOD_ANZEN, 		"Safety" },
	{ MOD_GAMEOVER, 	"Game Over" },
	{ MOD_GRAVITY, 		"Gravity" },
	{ MOD_WEED, 		"On To Grasstown" },
	{ MOD_MDOWN2, 		"Meltdown 2" },
	{ MOD_FIREEYE, 	"Eyes Of Flame" },
	{ MOD_VIVIA, 		"Gestation" },
	{ MOD_MURA, 		"Mimiga Village" },
	{ MOD_FANFALE1, 	"Fanfare 1" },
	{ MOD_GINSUKE, 		"Balrog's Theme" },
	{ MOD_CEMETERY, 	"Cemetery" },
	{ MOD_PLANT, 		"Yamashita Farm" },
	{ MOD_KODOU, 		"Pulse" },
	{ MOD_FANFALE3, 	"Fanfare 2" },
	{ MOD_FANFALE2, 	"Fanfare 3" }, // 0x10
	{ MOD_DR, 			"Tyrant" },
	{ MOD_ESCAPE, 		"Run!" },
	{ MOD_JENKA, 		"Jenka 1" },
	{ MOD_MAZE, 		"Labyrinth Fight" },
	{ MOD_ACCESS, 		"Access" },
	{ MOD_IRONH, 		"Oppression" },
	{ MOD_GRAND, 		"Geothermal" },
	{ MOD_CURLYA, 		"Cave Story" },
	{ MOD_OSIDE, 		"Moon Song" },
	{ MOD_REQUIEM, 	"Hero's End" },
	{ MOD_WANPAK2, 	"Scorching Back" },
	{ MOD_QUIET, 		"Quiet" },
	{ MOD_LASTCAVE, 	"Last Cave" },
	{ MOD_BALCONY, 		"Balcony" },
	{ MOD_LASTBTL, 	"Charge" },
	{ MOD_LASTBT3, 	"Last Battle" }, // 0x20
	{ MOD_ENDING, 		"The Way Back Home" },
	{ MOD_ZONBIE, 		"Zombie" },
	{ MOD_BDOWN, 		"Break Down" },
	{ MOD_HELL, 		"Running Hell" },
	{ MOD_JENKA2, 		"Jenka 2" },
	{ MOD_MARINE, 		"Living Waterway" },
	{ MOD_BALLOS, 		"Seal Chamber" },
	{ MOD_TOROKO, 		"Toroko's Theme" },
	{ MOD_WHITE, 		"White" },
	{ MOD_CAVE, 		"Pier Walk" },
	{ MOD_ROCKORG, 	"People of the Root" },
	{ MOD_KAZE, 		"Wind Fortress" },
    //{ NULL,    "Time Table" },
};

const song_info_def song_info_xm_d[SONG_COUNT] = {
	{ 0, 			    "Silence" },
	{ MOD_D_WANPAKU, 	"Mischievous Robot" },
	{ MOD_D_ANZEN, 		"Safety" },
	{ MOD_D_GAMEOVER, 	"Game Over" },
	{ MOD_D_GRAVITY, 	"Gravity" },
	{ MOD_D_WEED, 		"On To Grasstown" },
	{ MOD_D_MDOWN2, 	"Meltdown 2" },
	{ MOD_D_FIREEYE, 	"Eyes Of Flame" },
	{ MOD_D_VIVIA, 		"Gestation" },
	{ MOD_D_MURA, 		"Mimiga Village" },
	{ MOD_D_FANFALE1, 	"Fanfare 1" },
	{ MOD_D_GINSUKE, 	"Balrog's Theme" },
	{ MOD_D_CEMETERY, 	"Cemetery" },
	{ MOD_D_PLANT, 		"Yamashita Farm" },
	{ MOD_D_KODOU, 		"Pulse" },
	{ MOD_D_FANFALE3, 	"Fanfare 2" },
	{ MOD_D_FANFALE2, 	"Fanfare 3" }, // 0x10
	{ MOD_D_DR, 		"Tyrant" },
	{ MOD_D_ESCAPE, 	"Run!" },
	{ MOD_D_JENKA, 		"Jenka 1" },
	{ MOD_D_MAZE, 		"Labyrinth Fight" },
	{ MOD_D_ACCESS, 	"Access" },
	{ MOD_D_IRONH, 		"Oppression" },
	{ MOD_D_GRAND, 		"Geothermal" },
	{ MOD_D_CURLYA, 	"Cave Story" },
	{ MOD_D_OSIDE, 		"Moon Song" },
	{ MOD_D_REQUIEM, 	"Hero's End" },
	{ MOD_D_WANPAK2, 	"Scorching Back" },
	{ MOD_D_QUIET, 		"Quiet" },
	{ MOD_D_LASTCAVE, 	"Last Cave" },
	{ MOD_D_BALCONY, 	"Balcony" },
	{ MOD_D_LASTBTL, 	"Charge" },
	{ MOD_D_LASTBT3, 	"Last Battle" }, // 0x20
	{ MOD_D_ENDING, 	"The Way Back Home" },
	{ MOD_D_ZONBIE, 	"Zombie" },
	{ MOD_D_BDOWN, 		"Break Down" },
	{ MOD_D_HELL, 		"Running Hell" },
	{ MOD_D_JENKA2, 	"Jenka 2" },
	{ MOD_D_MARINE, 	"Living Waterway" },
	{ MOD_D_BALLOS, 	"Seal Chamber" },
	{ MOD_D_TOROKO, 	"Toroko's Theme" },
	{ MOD_D_WHITE, 		"White" },
	{ MOD_D_CAVE, 		"Pier Walk" },
	{ MOD_D_ROCKORG, 	"People of the Root" },
	{ MOD_D_KAZE, 		"Wind Fortress" },
    //{ NULL,           "Time Table" },
};

const song_info_def song_info_snes[SONG_COUNT] = {
    { 0,                            "Silence" },
    { MOD_SNES_MISCHIEVOUS_ROBOT,   "Mischievous Robot" },
    { MOD_SNES_SAFETY,              "Safety" },
    { MOD_SNES_GAMEOVER,            "Game Over" },
    { MOD_SNES_GRAVITY,             "Gravity" },
    { MOD_SNES_ON_TO_GRASSTOWN,     "On To Grasstown" },
    { MOD_SNES_MELTDOWN_2,          "Meltdown 2" },
    { MOD_SNES_EYES_OF_FLAME,       "Eyes Of Flame" },
    { MOD_SNES_GESTATIONA,          "Gestation" },
    { MOD_SNES_MIMIGA_TOWN,         "Mimiga Village" },
    { MOD_SNES_GOT_ITEM,            "Fanfare 1" },
    { MOD_SNES_BALROG,              "Balrog's Theme" },
    { MOD_SNES_CEMETERY,            "Cemetery" },
    { MOD_SNES_PLANT,               "Yamashita Farm" },
    { MOD_SNES_PULSE,               "Pulse" },
    { MOD_SNES_VICTORY,             "Fanfare 2" },
    { MOD_SNES_GET_HEART_TANK,      "Fanfare 3" },
    { MOD_SNES_TYRANT,              "Tyrant" },
    { MOD_SNES_RUN,                 "Run!" },
    { MOD_SNES_JENKA_1,             "Jenka 1" },
    { MOD_SNES_LABYRINTH_FIGHT,     "Labyrinth Fight" },
    { MOD_SNES_ACCESS,              "Access" },
    { MOD_SNES_OPPRESSION,          "Oppression" },
    { MOD_SNES_GEOTHERMAL,          "Geothermal" },
    { MOD_SNES_CAVE_STORY,          "Cave Story" },
    { MOD_SNES_MOONSONG,            "Moon Song" },
    { MOD_SNES_HEROS_END,           "Hero's End" },
    { MOD_SNES_SCORCHING_BACK,      "Scorching Back" },
    { MOD_SNES_QUIET,               "Quiet" },
    { MOD_SNES_LAST_CAVE,           "Last Cave" },
    { MOD_SNES_BALCONY,             "Balcony" },
    { MOD_SNES_CHARGE,              "Charge" },
    { MOD_SNES_LAST_BATTLE,         "Last Battle" },
    { MOD_SNES_THE_WAY_BACK_HOME,   "The Way Back Home" },
    { MOD_SNES_ZOMBIE,              "Zombie" },
    { MOD_SNES_BREAK_DOWN,          "Break Down" },
    { MOD_SNES_RUNNING_HELL,        "Running Hell" },
    { MOD_SNES_JENKA_2,             "Jenka 2" },
    { MOD_SNES_LIVING_WATERWAY,     "Living Waterway" },
    { MOD_SNES_SEAL_CHAMBER,        "Seal Chamber" },
    { MOD_SNES_TOROKOS_THEME,       "Toroko's Theme" },
    { MOD_SNES_WHITE,               "White" },
    { MOD_SNES_PIER_WALK,           "Pier Walk" },
    { MOD_SNES_PEOPLE_OF_THE_ROOT,  "People of the Root" },
    { MOD_SNES_WIND_FORTRESS,       "Wind Fortress" },
};