#include "common.h"
#include "bank_data.h"
#include "tables.h"

#include "soundbank.h"

const song_info_def song_info[SONG_COUNT] = {

};

const song_info_def song_info_xm[SONG_COUNT] = {
	{ 0, 			"Silence" },
	{ MOD_MISCHIEVOUS_ROBOT, 	"Mischievous Robot" },
	{ MOD_SAFETY, 		"Safety" },
	{ MOD_GAMEOVER, 	"Game Over" },
	{ MOD_GRAVITY, 		"Gravity" },
	{ MOD_ON_TO_GRASSTOWN, 	"On To Grasstown" },
	{ MOD_MELTDOWN_2, 	"Meltdown 2" },
	{ MOD_EYES_OF_FLAME, 	"Eyes Of Flame" },
	{ MOD_GESTATIONA, 	"Gestation" },
	{ MOD_MIMIGA_TOWN, 		"Mimiga Village" },
	{ MOD_GOT_ITEM, 	"Fanfare 1" },
	{ MOD_BALROG, 		"Balrog's Theme" },
	{ MOD_CEMETERY, 	"Cemetery" },
	{ MOD_PLANT, 		"Yamashita Farm" },
	{ MOD_PULSE, 		"Pulse" },
	{ MOD_VICTORY, 	"Fanfare 2" },
	{ MOD_GET_HEART_TANK, 	"Fanfare 3" }, // 0x10
	{ MOD_TYRANT, 		"Tyrant" },
	{ MOD_RUN, 			"Run!" },
	{ MOD_JENKA_1, 		"Jenka 1" },
	{ MOD_LABYRINTH_FIGHT, 	"Labyrinth Fight" },
	{ MOD_ACCESS, 		"Access" },
	{ MOD_OPPRESSION, 	"Oppression" },
	{ MOD_GEOTHERMAL, 	"Geothermal" },
	{ MOD_CAVE_STORY, 	"Cave Story" },
	{ MOD_MOONSONG, 	"Moon Song" },
	{ MOD_HEROS_END, 	"Hero's End" },
	{ MOD_SCORCHING_BACK, 	"Scorching Back" },
	{ MOD_QUIET, 		"Quiet" },
	{ MOD_LAST_CAVE, 	"Last Cave" },
	{ MOD_BALCONY, 		"Balcony" },
	{ MOD_CHARGE, 		"Charge" },
	{ MOD_LAST_BATTLE, 	"Last Battle" }, // 0x20
	{ MOD_THE_WAY_BACK_HOME, 	"The Way Back Home" },
	{ MOD_ZOMBIE, 		"Zombie" },
	{ MOD_BREAK_DOWN, 	"Break Down" },
	{ MOD_RUNNING_HELL, 	"Running Hell" },
	{ MOD_JENKA_2, 		"Jenka 2" },
	{ MOD_LIVING_WATERWAY, 	"Living Waterway" },
	{ MOD_SEAL_CHAMBER, 	"Seal Chamber" },
	{ MOD_TOROKOS_THEME, 		"Toroko's Theme" },
	{ MOD_WHITE, 		"White" },
	{ MOD_PIER_WALK, 		"Pier Walk" },
	{ MOD_PEOPLE_OF_THE_ROOT, 		"People of the Root" },
	{ MOD_WIND_FORTRESS, 		"Wind Fortress" },
    //{ NULL,    "Time Table" },
};


const song_info_def song_info_snes[SONG_COUNT] = {
    { 0,                            "Silence" },
    { MOD_SNES_MISCHIEVOUS_ROBOT,   "Mischievous Robot" },
    { MOD_SNES_SAFETY,              "Safety" },
    { MOD_SNES_GAMEOVER,            "Game Over" },
    { MOD_SNES_GRAVITY,             "Gravity" },
    { MOD_SNES_ON_TO_GRASSTOWN,     "On To Grasstown" },
    { MOD_SNES_MELTDOWN_2,          "Meltdown 2" },
    { MOD_SNES_EYES_OF_FLAME,       "Eyes Of Flame" },
    { MOD_SNES_GESTATIONA,          "Gestation" },
    { MOD_SNES_MIMIGA_TOWN,         "Mimiga Village" },
    { MOD_SNES_GOT_ITEM,            "Fanfare 1" },
    { MOD_SNES_BALROG,              "Balrog's Theme" },
    { MOD_SNES_CEMETERY,            "Cemetery" },
    { MOD_SNES_PLANT,               "Yamashita Farm" },
    { MOD_SNES_PULSE,               "Pulse" },
    { MOD_SNES_VICTORY,             "Fanfare 2" },
    { MOD_SNES_GET_HEART_TANK,      "Fanfare 3" },
    { MOD_SNES_TYRANT,              "Tyrant" },
    { MOD_SNES_RUN,                 "Run!" },
    { MOD_SNES_JENKA_1,             "Jenka 1" },
    { MOD_SNES_LABYRINTH_FIGHT,     "Labyrinth Fight" },
    { MOD_SNES_ACCESS,              "Access" },
    { MOD_SNES_OPPRESSION,          "Oppression" },
    { MOD_SNES_GEOTHERMAL,          "Geothermal" },
    { MOD_SNES_CAVE_STORY,          "Cave Story" },
    { MOD_SNES_MOONSONG,            "Moon Song" },
    { MOD_SNES_HEROS_END,           "Hero's End" },
    { MOD_SNES_SCORCHING_BACK,      "Scorching Back" },
    { MOD_SNES_QUIET,               "Quiet" },
    { MOD_SNES_LAST_CAVE,           "Last Cave" },
    { MOD_SNES_BALCONY,             "Balcony" },
    { MOD_SNES_CHARGE,              "Charge" },
    { MOD_SNES_LAST_BATTLE,         "Last Battle" },
    { MOD_SNES_THE_WAY_BACK_HOME,   "The Way Back Home" },
    { MOD_SNES_ZOMBIE,              "Zombie" },
    { MOD_SNES_BREAK_DOWN,          "Break Down" },
    { MOD_SNES_RUNNING_HELL,        "Running Hell" },
    { MOD_SNES_JENKA_2,             "Jenka 2" },
    { MOD_SNES_LIVING_WATERWAY,     "Living Waterway" },
    { MOD_SNES_SEAL_CHAMBER,        "Seal Chamber" },
    { MOD_SNES_TOROKOS_THEME,       "Toroko's Theme" },
    { MOD_SNES_WHITE,               "White" },
    { MOD_SNES_PIER_WALK,           "Pier Walk" },
    { MOD_SNES_PEOPLE_OF_THE_ROOT,  "People of the Root" },
    { MOD_SNES_WIND_FORTRESS,       "Wind Fortress" },
};